Numerical Python(Numpy)-Part 1

1.Numpy Dimension


In [4]:
import numpy as np 
a  = np.array([1,4,5,6], float)
a

array([1., 4., 5., 6.])

In [5]:
type(a)

numpy.ndarray

In [8]:
a.dtype

dtype('float64')

In [9]:
a.shape #차원수

(4,)

Array shape

In [28]:
#vector 1차원 데이터
vector = np.array([1,4,5,8])
vector.shape
#4 하나가 찍히므로 1차원

(4,)

In [24]:
#Matrix 2차원
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(matrix)
#2, 3 이 찍히므로 2 차원

(2, 3)
[[1 2 3]
 [4 5 6]]


In [25]:
#Tensor 3차원 이상
#tensor = np.array([[[],[]],[[],[]],[[],[]]])
tensor = np.arange(1, 25).reshape(2,3,4)
tensor


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [26]:
tensor.shape
#2, 3, 4 가 찍히므로 3 차원

(2, 3, 4)

In [27]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [29]:
#element의 갯수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [32]:
#data type
#float32 : 32bit로 표시 - single precision
#float64 : 64bit로 표시 -   precision
a=np.array([1,2,3], dtype=np.float32)
a


array([1., 2., 3.], dtype=float32)

In [35]:
b=np.array([1,2,3], dtype=np.int32)
b

array([1, 2, 3], dtype=int32)

### reshape


In [38]:
matrix.shape #(2 by 3)
matrix.reshape(6, ) #( 6은 튜플이 아니므로 ,를 붙여줘야함)

array([1, 2, 3, 4, 5, 6])

In [39]:
matrix.reshape(3,2) #3by 2로

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
matrix.reshape(-1, )  #-1 numpy가 알아서 맞춰줌 (단, size가 동일)

array([1, 2, 3, 4, 5, 6])

In [42]:
matrix.reshape(3, -1) #3만 정해주면 -1옵션을 줘 알아서 하게 만듬
matrix.shape

(2, 3)

In [46]:
tensor.reshape(4, -1).shape
tensor.reshape(3, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
tensor.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

flatten


In [52]:
tensor.reshape(-1, )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [55]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

##Indexing

In [57]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
matrix[0][1]

2

In [59]:
matrix[0, 1]

2

In [60]:
#tensordml 19찍고 싶다
tensor[1,1,2]

19

##slicing
시험문제 예상

In [63]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
#5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [65]:
#5,6,7 9,10,11
b[1:3, 1::]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [66]:
#1,3, 9, 11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [71]:
#2차원이상 대문자 1차원 소문자
X, y = b[:, :-1], b[:, -1]
