In [1]:
import numpy as np

In [ ]:
#1번
a = np.array([[10,20,30,40], np.array([50,60,70,80])])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
#2번 -1 
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
m[1, 2] #7값 인덱싱

7

In [ ]:
m[2, 4] #14값 인덱싱

14

In [ ]:
m[1, 1:3] #6, 7슬라이싱

array([6, 7])

In [ ]:
m[1:3, 2] #7, 12 슬라이싱 

array([ 7, 12])

In [ ]:
m[:2, 3:5]

array([[3, 4],
       [8, 9]])

In [ ]:
f = m.flatten()
for i in f:
    if i % 3 == 0 :
        print(i, end=',')


0,3,6,9,12,

In [ ]:
f = m.flatten()
for i in f:
    if i % 4 == 1 or i%3 == 0:
        print(i, end=',')

0,1,3,5,6,9,12,13,

In [ ]:
a = np.arange(4)
np.tile(a, (4, 1))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

#선생님 문제풀이

In [ ]:
#1번
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
#2번
m = np.arange(15).reshape(3,5)
m[1,2] #2-1
m[-1,-1] #2-2
m[1, 1:3] #2-3
m[1:, 2] #2-4
m[:2, 3:] #2-5

In [ ]:
#Boolean indexing
#3번
#3-1
f=m.flatten()
f[f%3==0]
#3-2
f[f%4==1]
#3-3
f[np.logical_and(f%3==0,f%4==1)]


In [ ]:
#eye로 행렬만들기
np.eye(5, 5, k=-1)*3 + np.eye(5,5)*2 + np.eye(5,5, k=1) #5 by5


array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

In [ ]:
# Matrix operation
np.random.seed(2021)
m = np.random.uniform(0, 10, 30).reshape(5,6).round(4) #0에서 10까지 30개 뽑기 5바이 6 
m


array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [ ]:
#5-1
np.max(m)
#5-2
np.sum(m, axis=1)
#5-3
np.max(m, axis=1)
#5-4
np.mean(m, axis=0)
#5-5
np.min(m, axis=0)


In [ ]:
#6번
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [ ]:
np.sort(score)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [ ]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [ ]:
#내림차순
s[::-1]

array([2, 1, 3, 0])

In [ ]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
#한번에 소팅하는 방법
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [ ]:
###7번 주사위 100번

In [ ]:
np.random.seed(2021)
dice = np.random.randint(1, 7, 100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [ ]:
np.mean(dice)


3.7

In [ ]:
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

연습문제 7

In [4]:
np.random.seed(2021)

price = 10000
rate = np.random.normal(0, 0.01, 10)
for i in range(10):
    price = price + np.round(price*rate[i])
    print(price, end=', ')

10149.0, 10218.0, 10175.0, 10093.0, 10149.0, 10077.0, 10191.0, 10257.0, 10268.0, 10311.0, 

In [5]:
np.random.seed(2021)
price_List = []
rate = np.random.normal(0, 0.01, 250)
price = 10000
for i in range(250):
    price += np.round(price * rate[i])
    price_List.append(int(price))
    

In [6]:
price_List[:10]

[10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257, 10268, 10311]