# Bag of Words

## 1. CountVectorizer

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you know I want your love. because I love you.']

In [12]:
cvector = CountVectorizer()

In [15]:
cvector.fit(corpus)      #학습
cvector.transform(corpus).toarray() #변환

array([[1, 1, 2, 1, 2, 1]])

In [16]:
cvector.vocabulary_

{'because': 0, 'know': 1, 'love': 2, 'want': 3, 'you': 4, 'your': 5}

In [17]:
cvector.fit_transform(corpus)

<1x6 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [20]:
output = cvector.fit_transform(corpus).toarray()
output


array([[1, 1, 2, 1, 2, 1]])

In [21]:
output.shape

(1, 6)

- 불용어를 제거한 BoW


In [22]:
# 사용자 정의 
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [23]:
#Scikit-Learn 제공
text=["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [25]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [26]:
from nltk.corpus import stopwords

text=["Family is not an important thing. It's everything."]
sw = stopwords.words("english")
vect = CountVectorizer(stop_words =sw)
print(vect.fit_transform(text).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [27]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key


In [31]:
get_word(2, vect.vocabulary_)

'important'

- N-gram

In [33]:
text1 = ['Machine learning is fun and not boring']
text2 = ['Machine is boring and learning is not fun']

In [34]:
#다른 문장이지만 카운트 벡터 쓰면 같은 결과가 나옴 따라서 N-gram을 같이 써야함
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text1).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'machine': 3, 'learning': 2, 'fun': 1, 'boring': 0}


In [35]:
vect = CountVectorizer(stop_words="english")
print(vect.fit_transform(text2).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1]]
{'machine': 3, 'boring': 0, 'learning': 2, 'fun': 1}


In [36]:
#N-gram range (1, 2)
vect = CountVectorizer(ngram_range=(1,2))
print(vect.fit_transform(text1).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1 1 1 1 1 1 1 1 1]]
{'machine': 9, 'learning': 7, 'is': 5, 'fun': 3, 'and': 0, 'not': 11, 'boring': 2, 'machine learning': 10, 'learning is': 8, 'is fun': 6, 'fun and': 4, 'and not': 1, 'not boring': 12}


In [37]:

print(vect.fit_transform(text2).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1 2 1 1 1 1 1 1 1 1]]
{'machine': 10, 'is': 5, 'boring': 2, 'and': 0, 'learning': 8, 'not': 12, 'fun': 4, 'machine is': 11, 'is boring': 6, 'boring and': 3, 'and learning': 1, 'learning is': 9, 'is not': 7, 'not fun': 13}


In [38]:
#N-gram range (1, 3)
vect = CountVectorizer(ngram_range=(1,3), stop_words="english")
print(vect.fit_transform(text1).toarray()) 
print(vect.vocabulary_)

[[1 1 1 1 1 1 1 1 1]]
{'machine': 6, 'learning': 3, 'fun': 1, 'boring': 0, 'machine learning': 7, 'learning fun': 4, 'fun boring': 2, 'machine learning fun': 8, 'learning fun boring': 5}


- Hyper parameter

In [39]:
vect.get_params() #파라메터들을 잘 써야함 

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': 'english',
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

- DTM

In [40]:
corpus = ["you know I want your love. because I love you.", "I like you","What should I do."] 
vect = CountVectorizer()
print(vect.fit_transform(corpus).toarray()) 
print(vect.vocabulary_)

[[1 0 1 0 2 0 1 0 2 1]
 [0 0 0 1 0 0 0 0 1 0]
 [0 1 0 0 0 1 0 1 0 0]]
{'you': 8, 'know': 2, 'want': 6, 'your': 9, 'love': 4, 'because': 0, 'like': 3, 'what': 7, 'should': 5, 'do': 1}


## TF-IDF vectorizer

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvect = TfidfVectorizer()
print(tvect.fit_transform(corpus).toarray().round(2)) 
print(tvect.vocabulary_)

[[0.31 0.   0.31 0.   0.62 0.   0.31 0.   0.47 0.31]
 [0.   0.   0.   0.8  0.   0.   0.   0.   0.61 0.  ]
 [0.   0.58 0.   0.   0.   0.58 0.   0.58 0.   0.  ]]
{'you': 8, 'know': 2, 'want': 6, 'your': 9, 'love': 4, 'because': 0, 'like': 3, 'what': 7, 'should': 5, 'do': 1}


In [49]:
tvect = TfidfVectorizer(ngram_range=(1,2), stop_words="english")
print(tvect.fit_transform(corpus).toarray().round(2)) 
print(tvect.vocabulary_)

[[0.33 0.33 0.   0.67 0.33 0.33 0.33]
 [0.   0.   1.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]]
{'know': 0, 'want': 5, 'love': 3, 'know want': 1, 'want love': 6, 'love love': 4, 'like': 2}


In [50]:
tvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 2),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}